"""phase5_expand_settings_add_notifications

Revision ID: 7af1d399f392
Revises: 001_initial_schema
Create Date: 2026-04-02 13:55:03.180750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af1d399f392'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('settings', sa.Column('push_notifications', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('settings', sa.Column('sms_alerts', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('settings', sa.Column('class_reminder_minutes', sa.Integer(), server_default='15', nullable=False))
    op.add_column('settings', sa.Column('exam_reminder_days', sa.Integer(), server_default='1', nullable=False))
    op.add_column('settings', sa.Column('assignment_reminder_hours', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'assignment_reminder_hours')
    op.drop_column('settings', 'exam_reminder_days')
    op.drop_column('settings', 'class_reminder_minutes')
    op.drop_column('settings', 'sms_alerts')
    op.drop_column('settings', 'push_notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
